language: python
python:
  - "3.4"
  - "2.7"

install:
 - pip -q install coveralls
 - pip install -r requirements.txt

script:  
 - if [[ $(python --version 2>&1) == "Python 2.7"* ]] ; then
        echo "running coverage";
        coverage run lineClipping.py;
   else
        python lineClipping.py;
   fi

after_success:
 - coveralls
