language: python
fast_finish: true

python: 
  - 3.6

os:
  - linux

sudo: required
dist: trusty
group: edge
  
env: 
  - FC=gfortran-6


notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gfortran-6

before_install:
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-6 40
  - pip -q install coveralls

install:
    - cd bin
    - cmake ..
    - make
    - cd ..
    
    - pip install -e .

script: coverage run tests/test.py -v

after_success: coveralls

