language: python
python:
  - "3.4"
  - "2.7"

install:
 - pip -q install coveralls
 - conda install --file requirements.txt

script:  
 - if [[ $CONDA == python=2.7* ]]; then
        coverage run lineClipping.py;
   else
        python lineClipping.py;
   fi

after_success:
 - coveralls
