language: python
python:
  - "3.4"
  - "2.7"
before_install: 
 - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - ./miniconda.sh -b
 - export PATH=/home/travis/miniconda/bin:$PATH
 - conda update --yes conda
 - pip install coveralls

install:
 - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy

script:  
 - if [[ $CONDA == python=2.7* ]]; then
		coverage lineClipping.py;
	else
		python lineClipping.py;
	fi

after_success:
 - coveralls
